#!/usr/bin/env python3
"""
Experiment 3 (real): benchmark JAX Adam, simulated annealing, QAOA, and
exact enumeration on the REAL branch-connectivity QUBO instances
generated by generate_real_qubo_instances.py, using the QUBO Hamiltonian
exactly as defined in Eq. (16) of the paper:

    H_QUBO(x) = -sum_{i,j} W_ij x_i x_j + lambda_pen * sum_i (1 - x_i)

(An earlier version of this experiment used a structurally different
MaxCut-style QUBO on synthetic random-graph instances; see Sec. VII.D
"Implementation status and open gaps" for that correction.)
"""

import sys
import json
import time
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT.parent / "data"

import numpy as np
import jax
import jax.numpy as jnp
import optax

from qiskit.quantum_info import SparsePauliOp
from qiskit.primitives import StatevectorSampler
from qiskit_algorithms import QAOA, NumPyMinimumEigensolver
from qiskit_algorithms.optimizers import COBYLA

LAMBDA_PEN = 1.0  # QUBO inactive-branch penalty, Eq. (16)


# ---------------------------------------------------------------------
# QUBO construction, exactly matching Eq. (16)
# ---------------------------------------------------------------------

def build_qubo_from_W(W, lambda_pen=LAMBDA_PEN):
    """
    H_QUBO(x) = -sum_{i,j} W_ij x_i x_j + lambda_pen * sum_i (1 - x_i)

    Expanding with W symmetric, W_ii = 0, x_i^2 = x_i:
        H = -2*sum_{i<j} W_ij x_i x_j - lambda_pen*sum_i x_i + const.
    QUBO dict convention: E(x) = sum_i Q_ii x_i + sum_{i<j} Q_ij x_i x_j
        Q_ii = -lambda_pen
        Q_ij = -2 * W_ij   (i<j)
    """
    n = W.shape[0]
    Q = {}
    for i in range(n):
        Q[(i, i)] = -lambda_pen
        for j in range(i + 1, n):
            if W[i, j] != 0:
                Q[(i, j)] = -2.0 * W[i, j]
    return Q


def qubo_energy(x, Q):
    energy = 0.0
    for (i, j), coeff in Q.items():
        energy += coeff * x[i] * x[j]
    return energy


def qubo_to_ising(Q, n):
    """QUBO -> Ising via x_i = (1 - Z_i)/2, matching Eq. (16)/Sec. V.D.2."""
    Q_mat = np.zeros((n, n))
    for (i, j), coeff in Q.items():
        Q_mat[i, j] = coeff
        if i != j:
            Q_mat[j, i] = coeff

    pauli_list, coeffs = [], []
    for i in range(n):
        h_i = 0.5 * Q_mat[i, i]
        for j in range(n):
            if i != j:
                h_i += 0.25 * Q_mat[i, j]
        if abs(h_i) > 1e-12:
            pauli_list.append("I" * i + "Z" + "I" * (n - i - 1))
            coeffs.append(-h_i)

    for i in range(n):
        for j in range(i + 1, n):
            qij = Q_mat[i, j]
            if abs(qij) > 1e-12:
                pauli_list.append("I" * i + "Z" + "I" * (j - i - 1) + "Z" + "I" * (n - j - 1))
                coeffs.append(0.25 * qij)

    if not pauli_list:
        return SparsePauliOp.from_list([("I" * n, 0.0)])
    return SparsePauliOp.from_list(list(zip(pauli_list, coeffs))).simplify()


# ---------------------------------------------------------------------
# Solvers
# ---------------------------------------------------------------------

def solve_jax(Q, n, n_iter=400, lr=0.05):
    Q_mat = np.zeros((n, n))
    for (i, j), coeff in Q.items():
        Q_mat[i, j] = coeff
    Q_jax = jnp.array(Q_mat)

    def loss(params):
        x = jax.nn.sigmoid(params)
        return jnp.dot(x, jnp.dot(Q_jax, x))

    key = jax.random.PRNGKey(42)
    params = jax.random.normal(key, (n,)) * 0.1
    optimizer = optax.adam(lr)
    opt_state = optimizer.init(params)
    grad_fn = jax.jit(jax.grad(loss))

    for _ in range(n_iter):
        grads = grad_fn(params)
        updates, opt_state = optimizer.update(grads, opt_state)
        params = optax.apply_updates(params, updates)

    x_opt = 1.0 / (1.0 + np.exp(-np.array(params)))
    x_binary = (x_opt > 0.5).astype(int)
    return qubo_energy(x_binary, Q), x_binary


def solve_sa(Q, n, n_sweeps=2000, n_reads=20, seed=42):
    rng = np.random.default_rng(seed)
    best_energy, best_x = float("inf"), None
    for _ in range(n_reads):
        x = rng.integers(0, 2, size=n)
        energy = qubo_energy(x, Q)
        T = 2.0
        for _ in range(n_sweeps):
            T *= 0.995
            i = rng.integers(0, n)
            x[i] = 1 - x[i]
            new_energy = qubo_energy(x, Q)
            delta = new_energy - energy
            if delta < 0 or rng.random() < np.exp(-delta / max(T, 1e-8)):
                energy = new_energy
            else:
                x[i] = 1 - x[i]
        if energy < best_energy:
            best_energy, best_x = energy, x.copy()
    return best_energy, best_x


def solve_qaoa(Q, n, reps=2, maxiter=50):
    hamiltonian = qubo_to_ising(Q, n)
    sampler = StatevectorSampler()
    optimizer = COBYLA(maxiter=maxiter)
    qaoa = QAOA(sampler=sampler, optimizer=optimizer, reps=reps)
    result = qaoa.compute_minimum_eigenvalue(hamiltonian)
    bitstring = result.best_measurement["bitstring"]
    x_le = np.array([int(b) for b in bitstring[::-1]])
    x_be = np.array([int(b) for b in bitstring])
    e_le, e_be = qubo_energy(x_le, Q), qubo_energy(x_be, Q)
    return (e_le, x_le) if e_le <= e_be else (e_be, x_be)


def solve_exact(Q, n):
    """Brute-force enumeration (fine for n<=10, 2^10=1024)."""
    best_energy, best_x = float("inf"), None
    for k in range(2 ** n):
        x = np.array([(k >> b) & 1 for b in range(n)])
        e = qubo_energy(x, Q)
        if e < best_energy:
            best_energy, best_x = e, x
    return best_energy, best_x


# ---------------------------------------------------------------------
# Main experiment loop
# ---------------------------------------------------------------------

def main():
    with open(DATA_DIR / "qubo_instances_real.json") as f:
        all_instances = json.load(f)

    out_path = DATA_DIR / "experiment3_real_results.json"
    if out_path.exists():
        with open(out_path) as f:
            results = json.load(f)
    else:
        results = {"n": [], "instances": []}

    target_n = sys.argv[1] if len(sys.argv) > 1 else None
    n_list = [target_n] if target_n else ["4", "6", "8", "10"]

    for n_str in n_list:
        if int(n_str) in results["n"]:
            print(f"N={n_str} already done, skipping.")
            continue

        n = int(n_str)
        instances = all_instances[n_str]
        print(f"\n>>> N = {n}  ({len(instances)} real branch-connectivity instances)")

        jax_e, sa_e, qaoa_e, exact_e = [], [], [], []

        for k, inst in enumerate(instances):
            W = np.array(inst["W"])
            Q = build_qubo_from_W(W)

            t0 = time.time()
            e_jax, _ = solve_jax(Q, n)
            e_sa, _ = solve_sa(Q, n, seed=k + 100)
            e_qaoa, _ = solve_qaoa(Q, n)
            e_exact, _ = solve_exact(Q, n)
            dt = time.time() - t0

            jax_e.append(float(e_jax))
            sa_e.append(float(e_sa))
            qaoa_e.append(float(e_qaoa))
            exact_e.append(float(e_exact))

            print(f"  inst {k} (seed={inst['seed']}, n_strong_scs={inst['n_strong_scs']}): "
                  f"JAX={e_jax:7.3f} | SA={e_sa:7.3f} | QAOA={e_qaoa:7.3f} | "
                  f"Exact={e_exact:7.3f}  ({dt:.1f}s)")

        results["n"].append(n)
        results["instances"].append({
            "jax": jax_e, "sa": sa_e, "qaoa": qaoa_e, "exact": exact_e,
        })

        with open(out_path, "w") as f:
            json.dump(results, f, indent=2)
        print(f"Checkpoint saved: {out_path}")

    print(f"\nAll requested sizes done. Saved: {out_path}")

    if len(results["n"]) == 4:
        print("\n=== Summary (mean +/- std) ===")
        print(f"{'N':>4} | {'JAX':>14} | {'SA':>14} | {'QAOA':>14} | {'Exact':>14}")
        order = sorted(range(len(results["n"])), key=lambda i: results["n"][i])
        for i in order:
            n, inst = results["n"][i], results["instances"][i]
            def ms(v):
                return f"{np.mean(v):.2f}+/-{np.std(v):.2f}"
            print(f"{n:>4} | {ms(inst['jax']):>14} | {ms(inst['sa']):>14} | "
                  f"{ms(inst['qaoa']):>14} | {ms(inst['exact']):>14}")


if __name__ == "__main__":
    main()
